// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByGDBF8od4Oej2T2mCcYXoa3PfTA-vaWY',
    appId: '1:521755054690:web:0b0b999040f7165043f73b',
    messagingSenderId: '521755054690',
    projectId: 'uber-fad71',
    authDomain: 'uber-fad71.firebaseapp.com',
    storageBucket: 'uber-fad71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAARJkRFbEGeaDMYOEQNGLh5UpMGWVdS1s',
    appId: '1:521755054690:android:f8c992a18d3c808643f73b',
    messagingSenderId: '521755054690',
    projectId: 'uber-fad71',
    storageBucket: 'uber-fad71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC-MT185KSXHWrx5rrt6fuf-X0Yt5OIgI',
    appId: '1:521755054690:ios:f0362d05fd5278bc43f73b',
    messagingSenderId: '521755054690',
    projectId: 'uber-fad71',
    storageBucket: 'uber-fad71.appspot.com',
    iosBundleId: 'com.example.uberlikeFlutterlearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC-MT185KSXHWrx5rrt6fuf-X0Yt5OIgI',
    appId: '1:521755054690:ios:f0362d05fd5278bc43f73b',
    messagingSenderId: '521755054690',
    projectId: 'uber-fad71',
    storageBucket: 'uber-fad71.appspot.com',
    iosBundleId: 'com.example.uberlikeFlutterlearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByGDBF8od4Oej2T2mCcYXoa3PfTA-vaWY',
    appId: '1:521755054690:web:89160dfd094f024f43f73b',
    messagingSenderId: '521755054690',
    projectId: 'uber-fad71',
    authDomain: 'uber-fad71.firebaseapp.com',
    storageBucket: 'uber-fad71.appspot.com',
  );
}
